version: '3.4'

services:
  test:
    image: dishttpgateway:0.1
    command: ["bash", "-c", "sleep infinity"]
    volumes:
      - ./:/app
    network_mode: "host"
    # ports:
    #   - 3000:3000/udp
    extra_hosts:
      - "polaris-online.c2n.adalfantln.marine.defensecdd.gouv.fr:127.0.0.1"
    # networks:
    #   - backend
  disgateway:
    image: dishttpgateway:0.1
    command: ["bash", "-c", "sleep infinity"]
    volumes:
      - ./:/app
    networks:
      - backend

networks:
  backend:
    name: c2n_polaris-online_private
    external: true
