version: '3.4'

services:
  test:
    image: python:3.11-slim
    command: ["bash", "-c", "sleep infinity"]
    volumes:
      - ./:/app
  disgateway:
    image: python:3.11-slim
    command: ["bash", "-c", "sleep infinity"]
    volumes:
      - ./:/app

